// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: controllers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countControllers = `-- name: CountControllers :one
SELECT count(*) FROM controllers
`

func (q *Queries) CountControllers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countControllers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createController = `-- name: CreateController :one
INSERT INTO controllers (name, mqtt_gateway_id, ip_address, location, is_active)
VALUES ($1, $2, $3, $4, COALESCE($5::boolean, true))
RETURNING id, name, mqtt_gateway_id, ip_address, location, is_active, created_at, updated_at
`

type CreateControllerParams struct {
	Name          string
	MqttGatewayID string
	IpAddress     *string
	Location      *string
	IsActive      *bool
}

// Явный ::boolean обязателен: без каста sqlc не выводит тип из COALESCE и генерирует
// interface{} вместо *bool.
func (q *Queries) CreateController(ctx context.Context, arg CreateControllerParams) (Controller, error) {
	row := q.db.QueryRow(ctx, createController,
		arg.Name,
		arg.MqttGatewayID,
		arg.IpAddress,
		arg.Location,
		arg.IsActive,
	)
	var i Controller
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MqttGatewayID,
		&i.IpAddress,
		&i.Location,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteController = `-- name: DeleteController :execrows
DELETE FROM controllers
WHERE id = $1
`

// :execrows — нужно количество затронутых строк, чтобы отличить успешное удаление
// от удаления несуществующего id (404).
func (q *Queries) DeleteController(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteController, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getController = `-- name: GetController :one
SELECT id, name, mqtt_gateway_id, ip_address, location, is_active, created_at, updated_at FROM controllers
WHERE id = $1
`

func (q *Queries) GetController(ctx context.Context, id uuid.UUID) (Controller, error) {
	row := q.db.QueryRow(ctx, getController, id)
	var i Controller
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MqttGatewayID,
		&i.IpAddress,
		&i.Location,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listControllers = `-- name: ListControllers :many

SELECT id, name, mqtt_gateway_id, ip_address, location, is_active, created_at, updated_at FROM controllers
ORDER BY created_at DESC, id
LIMIT $1 OFFSET $2
`

type ListControllersParams struct {
	Limit  int32
	Offset int32
}

// Запросы модуля controllers. Источник схемы — ../../db/migrations (см. sqlc.yaml).
// ORDER BY стабильный: без него LIMIT/OFFSET дают неопределённый порядок и строки
// могут дублироваться/пропадать между страницами. created_at не уникален, поэтому
// добиваем id как tie-breaker.
func (q *Queries) ListControllers(ctx context.Context, arg ListControllersParams) ([]Controller, error) {
	rows, err := q.db.Query(ctx, listControllers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Controller
	for rows.Next() {
		var i Controller
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MqttGatewayID,
			&i.IpAddress,
			&i.Location,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateController = `-- name: UpdateController :one
UPDATE controllers
SET
    name            = COALESCE($1, name),
    mqtt_gateway_id = COALESCE($2, mqtt_gateway_id),
    ip_address      = COALESCE($3, ip_address),
    location        = COALESCE($4, location),
    is_active       = COALESCE($5, is_active),
    updated_at      = now()
WHERE id = $6
RETURNING id, name, mqtt_gateway_id, ip_address, location, is_active, created_at, updated_at
`

type UpdateControllerParams struct {
	Name          *string
	MqttGatewayID *string
	IpAddress     *string
	Location      *string
	IsActive      *bool
	ID            uuid.UUID
}

// PATCH-семантика: NULL-параметр означает «поле не передано, не трогать».
// Ограничение: обнулить nullable-поле (ip_address/location) этим запросом нельзя —
// явный null неотличим от «не передано». Для MVP приемлемо; если понадобится —
// решать отдельными флагами или отдельным запросом, не усложняя этот.
func (q *Queries) UpdateController(ctx context.Context, arg UpdateControllerParams) (Controller, error) {
	row := q.db.QueryRow(ctx, updateController,
		arg.Name,
		arg.MqttGatewayID,
		arg.IpAddress,
		arg.Location,
		arg.IsActive,
		arg.ID,
	)
	var i Controller
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MqttGatewayID,
		&i.IpAddress,
		&i.Location,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
