// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// История срабатываний порогов алертинга (sensors.min_threshold/max_threshold)
type AlertEvent struct {
	// Первичный ключ
	ID uuid.UUID
	// Датчик, чьё показание вышло за порог
	SensorID uuid.UUID
	// Какой порог нарушен: min или max
	ThresholdType string
	// Значение порога на момент срабатывания (снимок sensors.min_threshold/max_threshold, независим от последующих правок порога)
	ThresholdValue float64
	// Значение показания, вызвавшее срабатывание
	ReadingValue float64
	// Момент срабатывания алерта
	TriggeredAt pgtype.Timestamptz
	// Момент возврата значения в допустимый диапазон, NULL — алерт ещё активен
	ResolvedAt pgtype.Timestamptz
}

// Физическое или виртуальное устройство (шлюз/ПЛК/ESP32), объединяющее один или несколько датчиков
type Controller struct {
	// Первичный ключ
	ID uuid.UUID
	// Человекочитаемое имя контроллера для дашборда, можно менять без влияния на приём MQTT-данных
	Name string
	// gateway_id из MQTT-топика gateway/{gateway_id}/{metric} — по нему Consumer сопоставляет входящее сообщение с контроллером
	MqttGatewayID string
	// IP-адрес устройства на площадке (справочно)
	IpAddress *string
	// Физическое расположение устройства (справочно)
	Location *string
	// Флаг активности контроллера
	IsActive *bool
	// Дата создания записи
	CreatedAt pgtype.Timestamptz
	// Дата последнего изменения записи
	UpdatedAt pgtype.Timestamptz
}

// Датчик, привязанный к контроллеру: MQTT-топик, тип метрики и пороги алертинга
type Sensor struct {
	// Первичный ключ
	ID uuid.UUID
	// Контроллер, к которому физически подключён датчик — обязателен, датчик без контроллера не существует
	ControllerID uuid.UUID
	// Человекочитаемое имя датчика для дашборда
	Name string
	// Уникальный MQTT-топик, на который датчик публикует показания
	Topic string
	// Тип измеряемой величины (temperature/humidity/pressure и т.д.), однозначно задан топиком
	MetricType string
	// Единица измерения (°C, Bar, % и т.д.)
	Unit string
	// Нижний порог значения для алертинга, NULL — порог не задан. Если оба порога заданы, min_threshold < max_threshold гарантировано CHECK
	MinThreshold *float64
	// Верхний порог значения для алертинга, NULL — порог не задан
	MaxThreshold *float64
	// Флаг активности датчика
	IsActive *bool
	// Дата создания записи
	CreatedAt pgtype.Timestamptz
	// Дата последнего изменения записи
	UpdatedAt pgtype.Timestamptz
}

// Hypertable TimescaleDB с показаниями датчиков, партиционирование по времени
type SensorReading struct {
	// Момент измерения (partitioning-колонка hypertable), входит в PRIMARY KEY
	Time pgtype.Timestamptz
	// Датчик, к которому относится показание
	SensorID uuid.UUID
	// Измеренное значение в единице измерения датчика (sensors.unit)
	Value float64
}

// Часовые агрегаты sensor_readings: используются дашбордом для длинных графиков и LLM Analytics для сводок без обращения к сырым данным
type SensorReadingsHourly struct {
	SensorID uuid.UUID
	Bucket   interface{}
	AvgValue float64
	MinValue interface{}
	MaxValue interface{}
	// Стандартное отклонение показаний за час — индикатор нестабильности датчика для LLM Analytics
	StddevValue float64
	// Количество показаний в часовом бакете
	ReadingCount int64
}

// Глобальные настройки системы в формате key-value (интервалы опроса, флаги функциональности и т.д.)
type SystemSetting struct {
	// Уникальный ключ настройки, первичный ключ таблицы
	Key string
	// Значение настройки (хранится как текст, парсится на уровне приложения)
	Value string
	// Пояснение назначения настройки
	Description *string
	// Дата последнего изменения значения
	UpdatedAt pgtype.Timestamptz
}

// Учётные записи, работающие с дашбордом и API
type User struct {
	// Первичный ключ
	ID uuid.UUID
	// Логин пользователя, уникален
	Username string
	// Почта пользователя, уникальна
	Email string
	// Хеш пароля (bcrypt), пароль в открытом виде не хранится
	PasswordHash string
	// Роль доступа: admin — полный доступ, operator — управление датчиками/контроллерами, viewer — только просмотр
	Role string
	// Дата создания учётной записи
	CreatedAt pgtype.Timestamptz
	// Дата последнего изменения записи
	UpdatedAt pgtype.Timestamptz
}
