// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sensors.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countSensors = `-- name: CountSensors :one
SELECT count(*) FROM sensors
WHERE ($1::uuid IS NULL OR controller_id = $1::uuid)
`

// Фильтр обязан повторять условие ListSensors: иначе total в ответе посчитается по всем
// датчикам и разойдётся с отфильтрованной страницей.
func (q *Queries) CountSensors(ctx context.Context, controllerID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSensors, controllerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSensor = `-- name: CreateSensor :one
INSERT INTO sensors (controller_id, name, topic, metric_type, unit, min_threshold, max_threshold, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($8::boolean, true))
RETURNING id, controller_id, name, topic, metric_type, unit, min_threshold, max_threshold, is_active, created_at, updated_at
`

type CreateSensorParams struct {
	ControllerID uuid.UUID
	Name         string
	Topic        string
	MetricType   string
	Unit         string
	MinThreshold *float64
	MaxThreshold *float64
	IsActive     *bool
}

// Явный ::boolean — без каста sqlc не выводит тип из COALESCE и генерирует interface{}.
func (q *Queries) CreateSensor(ctx context.Context, arg CreateSensorParams) (Sensor, error) {
	row := q.db.QueryRow(ctx, createSensor,
		arg.ControllerID,
		arg.Name,
		arg.Topic,
		arg.MetricType,
		arg.Unit,
		arg.MinThreshold,
		arg.MaxThreshold,
		arg.IsActive,
	)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.ControllerID,
		&i.Name,
		&i.Topic,
		&i.MetricType,
		&i.Unit,
		&i.MinThreshold,
		&i.MaxThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSensor = `-- name: DeleteSensor :execrows
DELETE FROM sensors
WHERE id = $1
`

// :execrows — нужно количество затронутых строк, чтобы отличить успешное удаление
// от удаления несуществующего id (404).
func (q *Queries) DeleteSensor(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSensor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSensor = `-- name: GetSensor :one
SELECT id, controller_id, name, topic, metric_type, unit, min_threshold, max_threshold, is_active, created_at, updated_at FROM sensors
WHERE id = $1
`

func (q *Queries) GetSensor(ctx context.Context, id uuid.UUID) (Sensor, error) {
	row := q.db.QueryRow(ctx, getSensor, id)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.ControllerID,
		&i.Name,
		&i.Topic,
		&i.MetricType,
		&i.Unit,
		&i.MinThreshold,
		&i.MaxThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSensors = `-- name: ListSensors :many

SELECT id, controller_id, name, topic, metric_type, unit, min_threshold, max_threshold, is_active, created_at, updated_at FROM sensors
WHERE ($3::uuid IS NULL OR controller_id = $3::uuid)
ORDER BY name, id
LIMIT $1 OFFSET $2
`

type ListSensorsParams struct {
	Limit        int32
	Offset       int32
	ControllerID *uuid.UUID
}

// Запросы модуля sensors. Источник схемы — ../../db/migrations (см. sqlc.yaml).
// Фильтр по контроллеру необязательный: NULL-параметр означает «все контроллеры».
// Тот же приём, что и для PATCH — одна ветка SQL вместо двух почти одинаковых запросов.
// ORDER BY стабильный (name не уникален, добиваем id) — иначе LIMIT/OFFSET дают
// неопределённый порядок и строки скачут между страницами.
func (q *Queries) ListSensors(ctx context.Context, arg ListSensorsParams) ([]Sensor, error) {
	rows, err := q.db.Query(ctx, listSensors, arg.Limit, arg.Offset, arg.ControllerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sensor
	for rows.Next() {
		var i Sensor
		if err := rows.Scan(
			&i.ID,
			&i.ControllerID,
			&i.Name,
			&i.Topic,
			&i.MetricType,
			&i.Unit,
			&i.MinThreshold,
			&i.MaxThreshold,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSensor = `-- name: UpdateSensor :one
UPDATE sensors
SET
    controller_id = COALESCE($1, controller_id),
    name          = COALESCE($2, name),
    topic         = COALESCE($3, topic),
    metric_type   = COALESCE($4, metric_type),
    unit          = COALESCE($5, unit),
    min_threshold = COALESCE($6, min_threshold),
    max_threshold = COALESCE($7, max_threshold),
    is_active     = COALESCE($8, is_active),
    updated_at    = now()
WHERE id = $9
RETURNING id, controller_id, name, topic, metric_type, unit, min_threshold, max_threshold, is_active, created_at, updated_at
`

type UpdateSensorParams struct {
	ControllerID *uuid.UUID
	Name         *string
	Topic        *string
	MetricType   *string
	Unit         *string
	MinThreshold *float64
	MaxThreshold *float64
	IsActive     *bool
	ID           uuid.UUID
}

// PATCH-семантика: NULL-параметр означает «поле не передано, не трогать».
// Ограничение то же, что у controllers: обнулить nullable-поле (пороги) этим запросом
// нельзя — явный null неотличим от «не передано».
func (q *Queries) UpdateSensor(ctx context.Context, arg UpdateSensorParams) (Sensor, error) {
	row := q.db.QueryRow(ctx, updateSensor,
		arg.ControllerID,
		arg.Name,
		arg.Topic,
		arg.MetricType,
		arg.Unit,
		arg.MinThreshold,
		arg.MaxThreshold,
		arg.IsActive,
		arg.ID,
	)
	var i Sensor
	err := row.Scan(
		&i.ID,
		&i.ControllerID,
		&i.Name,
		&i.Topic,
		&i.MetricType,
		&i.Unit,
		&i.MinThreshold,
		&i.MaxThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
